Tryout formik and yup
Itera/mad-learning-web pull request #78
Opened 2021-09-15 10:01 UTC by erlenste

New form with Formik and form validation with Yup.
Input validation on title, event type, starttime, endtime, description, location and image url.
This PR will (maybe) replace the EventForm with NewEventForm.
New components based on the ones used in EventForm has been created to accomodate Formik forms.

2021-09-15 13:36 UTC, erlenste commented
Typescript version was updated from 3.7.2 to 3.8.2 in this PR
Yup requires Typescript version > 3.8 to work

2021-09-15 14:13 UTC, sebastto reviewed
Nice validering! 👍
Har også et par småkommentarer, sjekk review

2021-09-15 14:13 UTC, sebastto commented on src/components/FormikFields/FormikInputField/styled.ts
> +export const EventError = styled.div`
Kan man bruke Formik sin komponent for ErrorMessage?
https://formik.org/docs/api/errormessage

2021-09-15 14:13 UTC, sebastto commented on src/components/NewEventForm/NewEventForm.tsx
> +  const parseDate = (date: string, time: string) => new Date(date + 'T' + time);
Er også en handy date string formatter i `src/utils/formatting.ts`

2021-09-16 08:41 UTC, anhtin requested changes
Nice work! There's only some minor stuff that needs to be changed in the name of readbility and easy maintenance 😝 

You might already be thinking of this, but I would just replace all relevant form and fields components with the new version instead of having two separate versions 😛

There's also some repetition in the formik field components that can be extracted into a base component. I'm thinking of `FormikContainer`, `FieldLabel` and `EventError`. The only variable part is really just the input element.

Finally, the `NewEventForm` component is way too large. You should look into how you can split it up into smaller parts to make it easier for a reader to digest the code.

2021-09-16 08:41 UTC, anhtin commented on src/components/NewEventForm/NewEventForm.tsx
> +  // Functions
This comment is incorrect

2021-09-16 08:41 UTC, anhtin commented on src/components/NewEventForm/NewEventForm.tsx
> +  const InitialValues = {
This name shouldn't be in PascalCase:
```suggestion
  const initialValues = { 
```

2021-09-16 08:41 UTC, anhtin commented on src/components/NewEventForm/NewEventForm.tsx
> +  const EventFormSchema = Yup.object().shape({
This name shouldn't be in PascalCase:
```suggestion
  const eventFormSchema = Yup.object().shape({
```

2021-09-16 08:41 UTC, anhtin commented on src/components/NewEventForm/NewEventForm.tsx
> +  });
This is a constant value, as such, it shouldn't live inside of the component (will cause unnecessary computation on each render)

2021-09-16 08:41 UTC, anhtin commented on src/components/NewEventForm/NewEventForm.tsx
> +          });
Large anonymous functions like this should be extracted into a named helper function instead. It improves readability 😄

2021-09-16 08:41 UTC, anhtin commented on src/components/NewEventForm/NewEventForm.tsx
> +              type = "text"
It's not normal to have a space between attributes/props name and value like this. You should use Prettier if you haven't already installed the plugin.
```suggestion
              label="Event name *"
              name="name"
              type="text"
```
There's more of these below

2021-09-16 08:41 UTC, anhtin commented on src/components/NewEventForm/NewEventForm.tsx
> +            <div style={{justifyContent:'center', display:'flex', alignItems: 'center', marginTop:'1rem'}}>
This styling should be extraced into a styled component. ref. the comment from @sebastto

2021-09-17 14:32 UTC, anhtin commented on src/components/EventForm/EventForm.tsx
> +      onSubmit={ async (values, { setSubmitting }) => {
Unnecessary spacing. You can configure Prettier to be automatically be ran after each save in your editor

2021-09-17 14:32 UTC, anhtin commented on src/components/EventForm/constants.ts
>        }
You should use `date-fns` here instead

2021-09-17 14:32 UTC, anhtin commented on src/components/EventForm/constants.ts
> +      }
Same as other comment: you should use `date-fns` here

2021-09-23 12:16 UTC, erlenste commented
Changes from 2nd review are implemented

2021-09-23 12:17 UTC, merged